// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGf_EtpUlRhl1yhtFG48CpOiBxQs5YClc',
    appId: '1:245795659576:android:a150a7fca3817519d42bcd',
    messagingSenderId: '245795659576',
    projectId: 'todo-app-6b608',
    storageBucket: 'todo-app-6b608.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0P-oxcsS1sbhvqvCkfXsLH4ayUTNuNNQ',
    appId: '1:245795659576:ios:0c2d15b1cd7c4737d42bcd',
    messagingSenderId: '245795659576',
    projectId: 'todo-app-6b608',
    storageBucket: 'todo-app-6b608.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeHqbz0A-DkSS3cHFykBvn8pO6PdqlPI8',
    appId: '1:245795659576:web:5414c7abc1f8e100d42bcd',
    messagingSenderId: '245795659576',
    projectId: 'todo-app-6b608',
    authDomain: 'todo-app-6b608.firebaseapp.com',
    storageBucket: 'todo-app-6b608.firebasestorage.app',
    measurementId: 'G-TD02R6GSR6',
  );
}
